apiVersion: v1
kind: ConfigMap
metadata:
  name: readmission-api-config
  namespace: readmission-mlops
data:
  APP_ENV: "production"
  MLFLOW_TRACKING_URI: "http://mlflow:5000"
  LOCAL_MODEL_PATH: "models/readmission_model.joblib"
