apiVersion: v1
kind: Secret
metadata:
  name: readmission-secrets
  namespace: readmission-mlops
type: Opaque
stringData:
  DATABASE_URL: "postgresql://readmission:readmission@postgres:5432/readmission"

